version: 2 # use CircleCI 2.0
workflows:
  version: 2
  test:
    jobs:
      - test-3.6
      - test-3.7
      - test-3.8
jobs: # A basic unit of work in a run
  test-3.6: &test-template
    # directory where steps are run
    working_directory: ~/meeshkan-examples
    docker: # run the steps with Docker
      # CircleCI Python images available at: https://hub.docker.com/r/circleci/python/
      - image: circleci/python:3.6.4-stretch
        environment: # environment variables for primary container
          PIPENV_VENV_IN_PROJECT: "true"
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: Install pipenv
          command: |
            sudo pip install pipenv
            pipenv update
            pipenv install -r ./requirements.txt
      - run:
          name: Run tests
          command: |
            python run_all.py
  test-3.7:
    <<: *test-template
    docker:
      - image: circleci/python:3.7.6-stretch
  test-3.8:
    <<: *test-template
    docker:
      - image: circleci/python:3.8.1-buster